#anytime we make use of docker, we need super user permissions

sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t gbdotcom/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gbdotcom/docker-react npm run test
  