#anytime we make use of docker, we need super user permissions

sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t gbdotcom/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gbdotcom/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-168697805315"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_SECRET